version: "3.7"
services:
  node:
    image: node:lts-alpine
    container_name: node
    working_dir: /app
    restart: always
    tty: true
    volumes:
      - .:/app
    ports:
      - 3000:3000
      - 3080:8080
