version: "3.7"
services:
  node:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: node
    volumes:
      - ./:/usr/src/app:cached
    working_dir: /usr/src/app
    command: sh
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
