version: "3.7"
services:
  httpd:
    image: httpd:latest
    volumes:
      - ./:/usr/local/apache2/htdocs/
    ports:
      - 8080:80
    restart: always
  node:
    container_name: node
    image: node:lts
    user: node
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app
    expose:
      - 8081
    tty: true
    restart: always
